id: PE864B856
initial_creation_type: ocr
source_metadata:
  volumes:
    93191f23823f421fb7817b1845c610b0:
      base_file: v057.txt
      image_group_id: I1PD95902
      title: ཡི་གེ་བརྒྱ་པ།
      total_pages: 1605
      volume_number: 57
